{
	provinces:[
	             {
	            	 name:'办公区',
	            	 citys:[
	            	          {name:'灯管'},
	            	          {name:'开关'},
	            	          {name:'插座'},
	            	          {name:'空调'},
	            	          {name:'家具'},
	            	          {name:'地毯'}	            	       
	            	       ]
	             },
	             {
	            	 name:'公共区',
	            	 citys:[
	            	          {name:'灯管'},
	            	          {name:'灯泡'},
	            	          {name:'开关'},
	            	          {name:'插座'},
	            	          {name:'饮水机'},
	            	          {name:'窗户'},	            	       
	            	          {name:'窗帘'},
	            	          {name:'纱窗'},
	            	          {name:'墙面'},
	            	          {name:'门'},
	            	          {name:'电梯'},
	            	          {name:'镜面'},	  
	            	          {name:'家具'},
	            	          {name:'指示牌'},
	            	          {name:'地面'}
	            	          ]     
	             },
	             {
	            	 name:'卫生间',
	            	 citys:[
	            	          {name:'灯管'},
	            	          {name:'插座'},
	            	          {name:'干手器'},
	            	          {name:'洗手液盒'},	            	       
	            	          {name:'排风机'},
	            	          {name:'顶棚'},
	            	          {name:'水龙头'},
	            	          {name:'面盆'},
	            	          {name:'蹲便'},
	            	          {name:'坐便'},	  
	            	          {name:'门'},
	            	          {name:'墙面'},
	            	          {name:'镜面'},
	            	          {name:'手纸盒'},
	            	          {name:'地面'}
	            	          ]     
	             },
	             {
	            	 name:'功能区',
	            	 citys:[
	            	          {name:'灯管'},
	            	          {name:'灯泡'},
	            	          {name:'开关'},
	            	          {name:'插座'},
	            	          {name:'家具'},
	            	          {name:'空调'},	            	       
	            	          {name:'窗帘'},
	            	          {name:'纱窗'},
	            	          {name:'墙面'},
	            	          {name:'门'},
	            	          {name:'硬件设施'},
	            	          {name:'地面'}
	            	          ]     
	             }
	]
}